module.exports = {
  USER_CONNECTED: 'USER_CONNECTED',
  SIMULATE_GAMEPLAY: 'SIMULATE_GAMEPLAY',
  SOCKET_EVENTS: [
    'USER_CONNECTED',
    'USER_DISCONNECTED',
  ],
  GET_USER_STATUS: 'GET_USER_STATUS',
  GET_USERS_OWN_STATS: 'GET_USERS_OWN_STATS',
  INITIALIZE_GAME: 'INITIALIZE_GAME',
  LEVEL_UP: 'LEVEL_UP',
  PAUSE: 'PAUSE',
  GET_NEXT_SHAPE: 'GET_NEXT_SHAPE',
  SCREEN_UPDATE: 'SCREEN_UPDATE',
  RAISE_FLOOR: 'RAISE_FLOOR',
  COLLISION: 'COLLISION',
  serverUrl: () => process.env.SERVER_URL || 'https://bears5.glitch.me/',
  clientUrl: () => process.env.CLIENT_URL || 'https://bears5.glitch.me/',
};
